### PR TITLE
Add 18F-branded USWDS to Tock

### PR DESCRIPTION
**Pull request by maya**
This adds 18F-branded USWDS to Tock, updating it's look and feel, and making some a11y improvements along the way.

Resolves: #478, #533, #521.
### Home page

tock home
### Weekly hours

4tyjnkbagqiecaaaecbagqiecaaaecbagqiecaaaecbagqiecaaaecbagqiebgqganobynjy1w6dklsly8fjuduj5rikcaaaecbagqiecaaaecbagqiecaaaecbagqiecaaaecbagqiecaaaecawi7cevvh6 ceb1e77y35gnlgsucbagqiecaaaecbagqiecaaaecbagqiecaaaecbagqiecaaaecbagqidagsnnq3n9f6ff7ywfhiswt
## TODO:
- [x] Add label to checkbox input on weekly hours submission page
- [x] Test with actual data to see if everything looks and works properly
- [x] Get design feedback from 18F brand team

### CODE REVIEW

**Comment by maya** [comment]
@jameshupp mentioned: 

>Only thing that’s a little awkward is the linebreak in "View Float assignments". It’s close enough to the `li` vertical spacing that at that line length it threw me a bit.

So we might want to increase the sidebar width so it all fits on one line.

**Comment by batemapf** [comment]
Code looks good. Clicked through on [staging](tock-staging.fr.cloud.gov), everything is functional and looks good.

Only concern I have (and this might not be due to this set of commits) is the lack of border at the left and right edges:

screen shot 2016-10-25 at 10 22 52 am

This was viewed at 100% zoom on Chrome. Bumping back to 90% looks better:

screen shot 2016-10-25 at 10 24 11 am

If this is unrelated to the commits or is just a 👻 in my machine, please disregard and we can address later!

**Comment by maya** [comment]
@batemapf thanks for the note! Added a fix for it here: 3f6605c, so while it still isn't fully responsive it will at least give you some padding on a slightly smaller screen.

screen shot 2016-10-25 at 3 55 45 pm

**Comment by annalee** [comment]
This is just waiting on comms to the team so no one's surprised by the changes.

**Comment by annalee** [comment]
Comms away! :shipit:

**Pull request merged**
