### PR TITLE
0-60 hours for superusers

### PR DESCRIPTION
**Pull request by Omnipresent**
This addresses #287 

I am beginning to work on https://micropurchase.18f.gov/auctions/12 and have a few questions. 
- I've got the development environment running, however, there are intermittent 502 errors. Has this been experienced before? Are there solutions to fix this? Below is an example

Image of Yaktocat
- The Readme.md mentions that by default the logged in user will be testuser@gsa.gov. Is this an admin user that is supposed to be able to enter > 40 hours?
- Is this the screen there the change needs to happen? If so, where should the checkmark go? The screenshot below shows an error when hours more than 40 hours were entered. 
  Image of Yaktocat

### CODE REVIEW

**Comment by adelevie** [comment]
Hi @Omnipresent, thanks for the questions. Here are our answers:

> I've got the development environment running, however, there are intermittent 502 errors. Has this been experienced before? Are there solutions to fix this? Below is an example

We're aware of these 502 errors, and there's no issue in production, so no need to worry about them.

> The Readme.md mentions that by default the logged in user will be testuser@gsa.gov. Is this an admin user that is supposed to be able to enter > 40 hours?

Two things:

1) Keep in mind that the superuser/admin does not actually enter more than 40 hours per week themselves. The superuser/admin designates which timecards (a join of user and reporting period) may have more than 40 hours.

2) It does not actually matter if testuser@gsa.gov can do this, all that matters is that any user, marked as a superuser or admin, can do this.

> Is this the screen there the change needs to happen? If so, where should the checkmark go? The screenshot below shows an error when hours more than 40 hours were entered.

Yes, this is the correct screen. We have no preference about location of the checkmark.

Hope all this helps!

**Comment by Omnipresent** [comment]
Hi @adelevie , thanks for the detailed explanation. 

Although there is no issue in production, it is extremely frustrating to develop in an environment that intermittently throws 502 errors. If you guys have a workaround, I would consider putting it in the Readme instructions. 

The latest commit should fulfill the requirement. Please let me know if anything additional is required from my end.

**Comment by Omnipresent** [comment]
Hi @adelevie , thanks for the detailed explanation.

Although there is no issue in production, it is extremely frustrating to develop in an environment that intermittently throws 502 errors. If you guys have a workaround, I would consider putting it in the Readme instructions.

The latest commit should fulfill the requirement. Please let me know if anything additional is required from my end.

**Comment by adelevie** [comment]
Hi @Omnipresent, we are currently reviewing this code, and will have more detailed feedback very soon.

In the meantime, we require that this code include tests that cover the new functionality. One of our acceptance criteria is that "Tests adequately cover any new functionality" (https://micropurchase.18f.gov/auctions/12). In this case, this means there should be at least some test coverage for the new zero-to-sixty hour behavior.

**Comment by adelevie** [comment]
Hi @Omnipresent, sorry about the 502 errors. We'll look into it and try to fix. It's bothering us, too.

We reviewed the code and have some feedback. In addition to the added test coverage, there are a few requirements missing in the currently delivered code:

1) The following requirement is not implemented:

```
Given superuser privileges in Tock,
When a superuser creates or edits a reporting period in the admin panel,

Then the superuser can give access to users to users who may enter between 0 and 60 hours for that reporting period.
```

(apologies for the typo--repeating "to users")

In the screenshot below, there is no way to designate which users may have a `zero_to_60` timecard for the new reporting period.
image

2) The following requirement is incomplete:

```
Given superuser privileges in Tock,
When a superuser views in the admin panel a time card for any other user,

Then the superuser would be able to select an option (e.g. check a box) which would allow any superuser to enter anywhere between 0 and 60 hours for a given week.
```

While the new validation logic is correct, there is a problem:

When editing a timecard that already exists that does not have 40 hours, and checking the `Zero to 60` checkbox, there is a validation error. See the following screenshots of the steps:

Editing a timecard with zero hours:
screen shot 2016-03-03 at 11 25 52 am

Checking the `Zero to 60` checkbox:
screen shot 2016-03-03 at 11 25 58 am

Result after clicking `save`
screen shot 2016-03-03 at 11 26 08 am

I suspect this is due to the fact that the new validation logic does not know to skip the `if hours > working_hours and not zero_to_60:` check when editing a pre-existing timecard.

We'll need these issues addressed before we can accept the delivered code. Perhaps the simplest way to fix these issues is to write test cases around them (which are required anyways). 

Please let us know if you have any more questions, and we're happy to keep reviewing code as you deliver it (if that helps!).

**Comment by Omnipresent** [comment]
Thanks for the feedback @adelevie I am working on the test cases right now but I don't see any existing test cases for this condition https://github.com/18F/tock/blob/master/tock/hours/admin.py#L43 I don't mind adding new test cases but can you tell me where the test cases should go?

**Comment by Omnipresent** [comment]
@adelevie I'm confused as to what the desired behavior is. The error message you showed in (2), exists even without the `zero_to_60` checkbox. The screenshots below show the same error with `zero_to_60` removed


screen shot 2016-03-03 at 7 39 27 pm
Result after clicking save
screen shot 2016-03-03 at 7 40 03 pm

Furthermore, there are errors when a project is picked but no hours are entered. The two screenshots below shot this error. 

Picking a project but not entering hours
screen shot 2016-03-03 at 7 40 26 pm
Result after clicking save
screen shot 2016-03-03 at 7 40 29 pm

The `zero_to_60` works fine when a project is selected and `0` hours are entered. The two screenshots below show this working

screen shot 2016-03-03 at 7 42 00 pm
 Result after clicking save
screen shot 2016-03-03 at 7 42 05 pm


Regarding the tests, I've added them in the latest commit

**Comment by Omnipresent** [comment]
@adelevie 
For the following requirement:

> Given superuser privileges in Tock,
> When a superuser creates or edits a reporting period in the admin panel,
> 
> Then the superuser can give access to users to users who may enter between 0 and 60 hours for that 

Is it suffice to show an admin list of users that they can pick which will have the `zero_to_60` permission. 

This list of users would be at the bottom of this screen.

screen shot 2016-03-03 at 7 39 27 pm

**Comment by adelevie** [comment]
Hi @Omnipresent,

We reviewed the code, and we're going to accept it. We apologize for some of the ambiguity in the second part of the acceptance criteria. We will learn from this; we want to ensure criteria is always clear and helpful to the vendor. The timecard editing functionality you created will help us tremendously, and we thank you for your work! I'll contact you offline regarding payment.

**Comment by Omnipresent** [comment]
Thanks for being helpful and supportive. This was our first micro-purchase and we look forward to contributing more in the future. Thanks

**Pull request closed without merging**
