### PR TITLE
Add Timecard Notes, admin improvements, and font fixes

### LINKED ISSUE #674: Fix FontAwesome fonts
It looks like the current FontAwesome setup is missing the actual font files, which is why we don't see things like the icons next to our report links.  D'oh!

### PR DESCRIPTION
**Pull request by ccostino**
Implements #672
Fixes #674 

This changeset adds support for adding global notes to all timecards, which can be enabled and disabled at any time.  In addition to this, the following other adjustments, improvments, and fixes have been made:

* Timecard notes now supported for all timecards; includes ability to enable and disable them, as well as select one of four styles
* Profit and Loss models are now bulk editable in the admin interface
* FontAwesome fonts are now fixed and loading correctly
* You can now search Profit and Loss models in the admin interface by accounting string, not just name

### CODE REVIEW

**Comment by ccostino** [comment]
Some screenshots of this in action!

Profit and Loss bulk update:
screen shot 2017-10-03 at 4 52 31 pm

Timecard Note bulk update:
screen shot 2017-10-03 at 4 52 42 pm

Timecard Note edit screen:
screen shot 2017-10-03 at 4 53 04 pm

Timecard notes displayed with timecard:
screen shot 2017-10-03 at 4 53 26 pm

Font/icon fixes/improvements:
screen shot 2017-10-03 at 5 04 47 pm

**Comment by ccostino** [comment]
One thing I wasn't sure of, and can be made in a later update, is if we still want the hardcoded message about when to enter time.  I kept it in for now, added a header, and all notes will show just below it.

**Comment by joshuabailes** [comment]
This is awesome!

**Comment by joshuabailes** [comment]
Will we gain control over the timecard note as well? The standard one?

**Comment by ccostino** [comment]
@joshuabailes we definitely can!  I'll submit another PR to take the hardcoded version out and try and supply it as a ready-made default.

**Pull request merged**
