### PR TITLE
Cloud Foundry forward-compatibility

### PR DESCRIPTION
**Pull request by mogul**
Per [Cloud Foundry documentation](https://docs.cloudfoundry.org/running/apps-enable-diego.html#app-code) use of `$VCAP_APP_HOST` and `$VCAP_APP_PASSWORD` are incompatible with newer (Diego-based) Cloud Foundry deployments. This change makes this repository forward compatible with the new cloud.gov environment deployment in AWS GovCloud.

### CODE REVIEW

**Comment by batemapf** [comment]
@mogul this looks pretty straightforward. for questions, we going to cloud.gov on github and/or slack?

**Comment by mogul** [comment]
If you've got any questions, you can hit us up at #cloud-gov-support in Slack.

**Comment by ccostino** [comment]
@mogul:  Is this change still applicable as is and necessary?  If so, I will merge!

**Comment by ccostino** [comment]
@mogul and I caught up, this is still necessary and better to get in place sooner rather than later before something stops working on us, so I am merging!

**Pull request merged**
