### PR TITLE
Travel Form and Email Request Automation

### PR DESCRIPTION
**Pull request by dsiddy**
This pull request fulfills the [Travel Form and Email Request Automation](https://micropurchase.18f.gov/auctions/14) micro-purchase.  Please see the commit history for detailed information.  All new code adheres to [PEP 8](https://www.python.org/dev/peps/pep-0008/).

Please let me know if you have any questions &mdash; and thanks again for this opportunity!

### CODE REVIEW

**Comment by adelevie** [comment]
Hi @dsiddy, this all looks good. We appreciate the descriptive commits and the test coverage. I'm still trying to get email sending to work locally.

We'd be happy to accept right away if you add a passing integration test before the delivery deadline (6:00 pm). That said, if you don't, I'm going to spend a little more time (probably next week) manually testing that functionality. If the email sending works, we'll accept.

And I just want to clarify, we're not requiring the addition of this integration test. We're erring on the side of you, the vendor, since we didn't specifically require that integration test (only that tests be "adequate"). In my judgment, the form validation tests you shipped are adequate.

**Comment by adelevie** [comment]
Hi @dsiddy,

I manually verified that the email function works:

```
Hello,

    I request approval to travel from dc to atl.  The dates of travel are April 30, 2016 - June 30, 2016.  I will depart the April 30, 2016, to arrive in time for work work work scheduled for May 12, 2016.  I will return to dc on June 30, 2016.

    Please reply with your approval, or with any subsequent clarifications you may have.

Many thanks,
c9yD4f FLFi9d
``` 

We accept your micro-purchase. I'll contact you offline to discuss payment. Thanks for the contribution!

**Comment by dsiddy** [comment]
Excellent!  Thanks, @adelevie.  I'm still inclined to provide you with an integration test, so please don't be surprised if I follow up with another pull request.

**Comment by mtorres253** [comment]
@toolness would you have some time to look at this? It's an old pull request but will add some value and scale to ops. It will require a rebase and some work to bring it up to date with the existing codebase, but shouldn't be too terrible. @sfvictor @joshuabailes can fill you in on the business value. Also cc @jessieay and @adelevie

**Comment by ccostino** [comment]
@mtorres253, @batemapf, and @abrouilette:  I'm closing this PR in favor of #425 since the new one fixes the merge conflicts.  Thanks!

**Pull request closed without merging**
