### PR TITLE
replace our beloved sean with our fearless leader

### PR DESCRIPTION
**Pull request by batemapf**
re: #271.

cc @jackiekazil @seanherron @aaronsnow

### CODE REVIEW

**Comment by ccostino** [comment]
Awesome!  Should the `tock/tock/fixtures/dev_user.json` be updated as well to mirror the `tock/tock/fixtures/prod_user.json` fixture to a degree, or could/should it be removed all together?  The reason I ask is because loading one of these fixtures fixes #236. :-)

**Comment by batemapf** [comment]
@ccostino i think we can toss the `dev_user.json`.  i'll update the PR...

**Comment by ccostino** [comment]
Yikes, it looks like that fixture was being used by a bunch of the tests?

**Comment by batemapf** [comment]
arg. i'll tidy

**Comment by seanherron** [comment]
Should have just left me in my rightful place.

**Comment by batemapf** [comment]
@seanherron speaks!!!!

**Comment by batemapf** [comment]
woohoo!!! @ccostino or others please merge if things look good

**Comment by ccostino** [comment]
Awesome, thanks @batemapf!

**Comment by jackiekazil** [comment]
:us:

**Pull request merged**
