### PR TITLE
Improve display of alerts

### LINKED ISSUE #379: alerts stacking up!
screen shot 2016-06-17 at 6 00 37 pm

as a user, when i select one project that has an alert, but then change my project to another that also has an alert, the first alert does not clear.

### LINKED ISSUE #399: burn rate alert not clear about which project it corresponds to
This feature is great—just saw it for the first time! My only feedback is that it isn't clear whether it corresponds to the project above or below. Increasing the whitespace above/below or putting a border around the warning+field would help.

Tock screenshot

### PR DESCRIPTION
**Pull request by ccostino**
Fixes #379
Fixes #399

This changeset improves the display of alerts and notes so that they are grouped with their associated project line item in the time entry form.  It also fixes a bug where the change event was being registered on all selection menus exponentially with each additional line item added dynamically.

The display of the alerts is changed such that each row containing a line item will alternate in color between white and a light shade of gray.

I've tried to take into account accessibility concerns regarding the colors and hopefully have found a happy medium between proper contrast and decent colors.  I hesitate to spend more time on that as it would be getting into the realm of dealing with Tock's overall visual design and user experience, which could very much benefit from the eyes and expertise of one of our great designers.  Hopefully at some point in the future this is something we can address. :-)

/cc @batemapf, @afeld

### CODE REVIEW

**Comment by ccostino** [comment]
A preview of what this looks:

screen shot 2016-07-12 at 11 30 54 am

**Comment by afeld** [comment]
Dunno if the darker grey will be an accessibility issue, but solves my issue, thanks!

**Comment by ccostino** [comment]
Ah good call - I should also point out that I set this up to alternate the color between rows.  @nickbristow, if you wouldn't mind, could you please take a quick look whenever you a free moment and provide any additional feedback regarding potential accessibility issues with this?  Thank you!

**Comment by batemapf** [comment]
@ccostino holding off on this one until you get some feedback re: accessibility. sound good?

**Comment by ccostino** [comment]
@batemapf: Sounds good!

**Comment by toolness** [comment]
By "accessibility" do you mean the color contrast ratio?

The [black on gray](http://leaverou.github.io/contrast-ratio/#black-on-%23DDDDDD) has a ratio of 15.5, which is great.  red on black isn't as good at [2.3](http://leaverou.github.io/contrast-ratio/#red-on-%23DDDDDD) but it *is* bold red, which I think lowers the minimum threshhold for the ratio (the preferred ratio is 4.5 i think).

**Comment by ccostino** [comment]
Oh awesome, thanks for the heads up @toolness and the links to the tool to check the contrast!  I'll double check these things to see.

**Comment by toolness** [comment]
Sure thing!

A better color than `red` for the warning might be `crimson`.  The contrast ratio on gray is [3.7](http://leaverou.github.io/contrast-ratio/#crimson-on-%23DDDDDD) which passes WCAG AA for "large text", which includes bold text above 14pt.

**Comment by ccostino** [comment]
@toolness, thanks again!  I think I've addressed the color concerns here.  Tock could definitely use a visual designer at this point for much better color choices and overall improvements, but that's neither here nor there.  Working with what we have currently, this should help address the main concerns at least.

@batemapf, this is ready for review again!

**Comment by ccostino** [comment]
Here's an updated preview of what some of this looks like:

screen shot 2016-07-13 at 12 58 34 pm

**Comment by batemapf** [comment]
@ccostino minor color change. in addition, tried to get everything to line up nicely on the right side. couldn't figure out how to do it :-( see below:

screen shot 2016-07-14 at 10 19 15 am

thoughts?

**Comment by ccostino** [comment]
@batemapf: I tried to account for that too, something weird is going on with the CSS and layout.  I'll try taking another look to see if I can fix it.

**Comment by batemapf** [comment]
if we only had a front end dev...

On Thu, Jul 14, 2016 at 11:46 AM, Carlo Costino <notifications@github.com>
wrote:

> @batemapf <https://github.com/batemapf>: I tried to account for that too,
> something weird is going on with the CSS and layout. I'll try taking
> another look to see if I can fix it.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/18F/tock/pull/400#issuecomment-232705330>, or mute
> the thread
> <https://github.com/notifications/unsubscribe/AHSosqtX3I1gPfSUwz0vANrAKV7rkabJks5qVlnZgaJpZM4JKhM8>
> .
>



-- 
Patrick F. Bateman
Operations Director
18F
U.S. General Services Administration

**Comment by ccostino** [comment]
Or just time!

**Comment by ccostino** [comment]
I haven't forgotten about this, just haven't had a chance to dive back into it yet - I will as soon as I have free moment!

**Comment by nickbristow** [comment]
@ccostino Hello, i've been off for a week. 

Do you have a screen shot of the change, or is this live somewhere i can look at?

**Comment by ccostino** [comment]
Hi @nickbristow!  I don't think this is live anywhere, but there is a preview screen shot a few comments above.  I'd be happy to go over this at some other point when we're both free via Screenhero or something if that'd be easier.  Or this could be deployed to tock-staging if @batemapf is okay with that (I'll make sure the branch is updated first).

**Comment by nickbristow** [comment]
@ccostino ah ok, I don't see an issue with it, doesn't appear to have any test in the grey box so its all good on that front.

**Comment by batemapf** [comment]
+1 to deploying to tock-staging. let me know if you need me to do it. just
making sure you are pointing at the right cf space!

**Comment by ccostino** [comment]
This is deployed to `tock-staging` for further review!

**Comment by ccostino** [comment]
@batemapf and @toolness, this is now good to go and fixes another outstanding issue.  I realize that it could definitely use even more style/UI love.

**Comment by batemapf** [comment]
deployed.

**Pull request merged**
