### PR TITLE
remove pagination_class from ProjectList view

### PR DESCRIPTION
**Pull request by batemapf**
to address pagination issue in #363

### CODE REVIEW

**Comment by batemapf** [comment]
hrmm. tests run fine locally. another `n +1` issue, though not sure of similarity to @ccostino issue with #357. ❓

**Comment by ccostino** [comment]
Ah!  No nplusone errors will be raised if it's not set to do so in the corresponding environment config.  It's not enabled in the `dev` settings, which are used locally.  It is enabled in `test`, which Travis CI uses:  https://github.com/18F/tock/blob/master/tock/tock/settings/test.py#L17

As for what's actually throwing the error, I'd have to look a bit more to see where the queryset is being accessed.  It's the same issue that I was dealing with in terms of the cause of the test failing (a many-to-many relationship between models), but this is a different part of the code.

I do wonder if merging the PR I have open and then merging those updates back into here would also fix the issue - I will try and get that last issue we saw last night either resolved or explained so we can move ahead with it, because the PR contains and update to nplusone as well.

**Comment by jmcarp** [comment]
This is a fun issue. What it all boils down to is that `TimecardView.last_timecard` loads more data than it needs to: https://github.com/18F/tock/blob/master/tock/hours/views.py#L171-L178. The trick is that calling `if timecards` loads *all* results in the `timecards` queryset, even though we only want the last one. Since we're then lazy-loading relations of the last timecard, we get a lazy-load warning. This is fixed in #357, which calls `first` on the queryset instead of loading all records and returning the 0th one: https://github.com/18F/tock/blob/382e70195ff66470a03097c14bff84dd67d0bfe2/tock/hours/views.py#L171-L178.

**Comment by batemapf** [comment]
all fixed. thanks again @jmcarp and @ccostino

**Pull request merged**
