### PR TITLE
Project view by Engagement Management lines

### PR DESCRIPTION
**Pull request by neilmb**
## Description

This addresses #1243 by adding a new view at `projects/engagement`. It lists only active projects that have "matching" engagement management lines where matching means the engagement management line ends with "Engagement Management" and it starts with the full name of another project line. (This does miss some pairs where they don't use exactly the same names.) 

The total number of hours billed for the project and EM line are computed and the projects are listed in descending order of the ratio of those hours (more relative engagement management time is listed first).

## Additional information

Screen Shot 2021-03-10 at 10 47 24

### CODE REVIEW

**Review by Jkrzy — CHANGES_REQUESTED** [review]
Thanks @neilmb this is a super interesting hypothesis to test!

We're missing a navigable path to these reports from the interface, let's add a link from the `View Reports` drop down.

**Comment by Jkrzy** [comment]
After this rolls out, let's set a check-in point a month or so into the future to evaluate if this is an informative way to look at project tocking. At that time we'll chat with the COO and make a decision on a next iteration or retiring this.

**Comment by kfoley-18F** [comment]
I would like to get this merged soon. @neilmb - do you have time to add a nav link? Joe had suggested to the View Reports dropdown, I can also see making View Projects a dropdown instead of a static menu item, and having "All Projects" go to the current view and "Project reports" go to this one. (or something similar...) If you are buried, let me know and I'll get some other dev help for picking up this item and getting it over the line. 

Many thanks for this!!!

**Comment by neilmb** [comment]
Added a second-level menu for "View Projects" and used the names "All Projects" for `/projects/` and "Engagement Levels" for `/projects/engagement/`. Happy to change the names if they are not clear.

Screen Shot 2021-07-28 at 09 33 10

**Comment by neilmb** [comment]
@kfoley-18F Changed as requested, tests finally pass, ready for re-review.

**Review by kfoley-18F — APPROVED** [review]
W00t! thank you!!
LGTM

**Comment by kfoley-18F** [comment]
@Jkrzy - does this satisfy your change request??

**Review by Jkrzy — APPROVED** [review]

**Pull request merged**
