### PR TITLE
Improve timecard form UX

### PR DESCRIPTION
**Pull request by ccostino**
Address #804 

This changeset is an attempt to improve the user experience a bit around the buttons and info/error messages when saving or submitting the form.  Specifically, it addresses the following:

* Swaps the order of the save and submit buttons
* Makes the submit button noticeably larger
* Changes the style of the save button to be a secondary button
* Shifts form info and error messages to appear at the top and bottom of the timecard for improved visibility
* Provides alert titles to the messages displayed
* Fixes the display of most alerts
* Adds a submission success mesage

This is just a start; more improvements can certainly be made!

### CODE REVIEW

**Comment by ccostino** [comment]
Hopefully this will help some with the user experience folks have when submitting time cards!  Here are some screenshots of the changes:

New buttons
screen shot 2018-05-14 at 12 03 58 pm

New notifications
screen shot 2018-05-14 at 11 52 05 am
screen shot 2018-05-14 at 12 04 25 pm

New notification on reporting period list after submitting a time card
screen shot 2018-05-14 at 12 22 03 pm

**Comment by ccostino** [comment]
I've made some additional improvements to this!  Brought to you while listening to The Final Countdown and Eye of the Tiger among other things of that nature...

Saving the time card:
screen shot 2018-05-14 at 11 07 15 pm

Submitting the time card:
screen shot 2018-05-14 at 11 07 34 pm

:-)

**Comment by ccostino** [comment]
Last improvement and then it's off to bed for me, because Sweet Dreams (Are Made of This)...

Improved error alert!
screen shot 2018-05-14 at 11 17 01 pm

**Comment by line47** [comment]
These changes are great @ccostino I love the better alerts and different button styles! ❤️ 

One thing to note is that some folks were previously having issue of accidentally submitting their timecard which is why the save action was first and the submit action was second. Ideally i think some sort of way for folks not to be able to submit until appropriate hours are met would be a great addition to help stop some of those accidental submissions.

**Comment by ccostino** [comment]
Thanks so much for taking a look, @line47! :-)

I know what you mean about the buttons and folks still accidentally submitting when they're not done; this was the best I could do given what I was seeing and some of the feedback given.  Tock will prevent you from submitting if you have too few or too many hours, but that's about it.

Do you think it'd be better to keep the order of the buttons as they were but with the new styles and text?  Or does it make more sense with them swapped again?

Our time is limited on this and I caught a bit of a break while at PyCon to work through these things, but if you'd like to expand on your thoughts a bit about restricting submissions and file an issue, we'd appreciate it! :-)

Thanks again for taking a look!

**Comment by line47** [comment]
Maybe leave it for now and see if the issue comes back up about accidental submissions. If it does then switch the order to save first with submit second 👍

**Comment by ccostino** [comment]
Awesome, sounds good to me! :-)

**Pull request merged**
