### PR TITLE
WIP alternate work schedule code. DO NOT MERGE.

### PR DESCRIPTION
**Pull request by annalee**
## Description

Allows admins to set working hours on a user-by-user basis, so that staff on alternate work schedules don't get prompted to log 40 hours each week.

TODO:
[ ] Finish refactoring out previous, non-user-specific working hours code
  [ ] clean up old working hours on admin
  [ ] clean up old working hours tests
[ ] Add new working hours tests
[ ] Improve hours validation?

## Additional information

Include any of the following (as necessary):

* Relevant research and support documents
* Screenshot images
* Notes

### CODE REVIEW

**Comment by ccostino** [comment]
@annalee:  Should we move forward on this and if so, is there a time we can catch up to review and discuss, especially in light of yesterday's conversation?

**Comment by tbaxter-18f** [comment]
@ccostino did you have a chance to have that conversation with @annalee? Should this be closed?

**Comment by ccostino** [comment]
No, we never did.  @abrouilette, is there any need for this?  If not, let's close.

**Comment by tbaxter-18f** [comment]
I didn't realize this was nearly a year old. Given that age and how much has moved underneath, I'm going to close it. If it does turn out this is a desire, we'd probably have to take a fresh run at it anyway.

**Pull request closed without merging**
