### PR TITLE
Limit to 5 recent periods in table on project detail page

### PR DESCRIPTION
**Pull request by brendansudol**
This PR addresses [issue #289](https://github.com/18F/tock/issues/289), the micro-purchase auction to "Fix data visualization in Tock user interface". 

This code limits the number of time periods displayed in the table in the project detail page (/projects/:id) to the five most recent time periods by filtering the data in the `project_timeline` method in `project/views.py`. 

New unit tests for this functionality can be found in `projects/tests.py`.

All new code is [PEP 8](https://www.python.org/dev/peps/pep-0008/) compliant.

### CODE REVIEW

**Comment by adelevie** [comment]
This PR does not degrade accessibility:
`master`
screen shot 2016-01-19 at 11 41 01 am
This PR:
screen shot 2016-01-19 at 11 40 46 am

**Comment by brendansudol** [comment]
glad to hear it :+1:

**Comment by adelevie** [comment]
LGTM. We accept.

:ship:

**Comment by brendansudol** [comment]
awesome, thanks!

**Pull request merged**
