### PR TITLE
First take at sorting reporting by org.

### PR DESCRIPTION
**Pull request by tbaxter-18f**
## Description

First take on #968, attempting to sort by org name. Because there's a fairly gnarly relationship out to org, I'm kinda hesitant to do more sophisticated reporting.

This is hard to test as you have to find a reporting period:  http://localhost:8000/reports/2015-08-16/ 
And you also have to apply org data to multiple users, which don't currently have it. If you can pick it up and fully test it, I'd appreciate it.

### CODE REVIEW

**Comment by Jkrzy** [comment]
Thanks @tbaxter-18f!! I'll pick this one up!

**Comment by Jkrzy** [comment]
Tiny step in the right direction for #968 ahead of adding inputs and true sorting/filtering UX interactivity. 

We're adding Organization name to the sorting for all displays on the `Reports` page. With this change, each table is now sorted by Organization Name, Last Name, and then First Name.

`18F` will render as the first organization in the table.

**Comment by tbaxter-18f** [comment]
LGTM, but since I started it I'll wait for @amymok to approve. Thanks for picking it up, Joe!

**Comment by amymok** [comment]
There's no changes in dependency, Snyk is being funky here for pending.  Will bypass and merge.

**Pull request merged**
