### PR TITLE
Pre-populate projects for new timecards + delete functionality

### PR DESCRIPTION
**Pull request by brendansudol**
This PR addresses [issue #308](https://github.com/18F/tock/issues/308) and micro-purchase [auction #15](https://micropurchase.18f.gov/auctions/15) to "Reload Tock Projects in new reporting period". 

When a user opens a reporting period timesheet that has no entries, it attempts to pre-populate the form with the projects from the last submitted timecard (if there is one). While the projects are carried over, the hours are left blank, and project entries can now be deleted for unsubmitted timecards.

One thing to note: in the spec, it states that the project pre-population should occur when a new timesheet is opened. However, this could lead to a situation where you open a new timesheet to see the projects from the last timecard (as desired), but if you then reload the page the projects would go away (because the timesheet is no longer "new" as it was created on the last request. This could perhaps be confusing to the user and for that reason, I implemented it such that the project pre-population occurs for a timesheet as long as there are no saved entries for that timesheet. This way, if you reload the page after opening a new timesheet, the projects will persist (and if you then add hours and save any of those projects, the pre-population will no longer occur and instead the saved entries will be loaded). Let me know what you think about this solution. It's a very trivial change if we want to just show the pre-populated projects only once on the initial creation.

New unit tests for this functionality can be found in `tock/hours/tests/test_views.py`.

All new code is [PEP 8](https://www.python.org/dev/peps/pep-0008/) compliant.

### CODE REVIEW

**Comment by brendansudol** [comment]
Hi @adelevie -- just wanted to check in re: this PR. Let me know if there's any additional info I can provide.

**Comment by adelevie** [comment]
Hi @brendansudol,

I was drafting this very message when you just asked that.

We accept the delivery. Thanks again for participating in micro-purchase. I'll contact you offline about payment.

**Comment by brendansudol** [comment]
Haha -- I guess my :ear:s were burning :smile: Thanks for organizing!

**Comment by adelevie** [comment]
Needs a rebase, @brendansudol :)

**Comment by brendansudol** [comment]
survived the rebase with minimal scarring @adelevie -- let's get this puppy merged!

**Comment by adelevie** [comment]
@batemapf, this awaits your approval.

**Comment by brendansudol** [comment]
alright, we're ready again @adelevie and @batemapf -- it's go time!

**Comment by batemapf** [comment]
woohoo! thanks @brendansudol!

**Comment by porta-antiporta** [comment]
:tada:

**Pull request merged**
