### PR TITLE
Fix color contrast for report period totals area

### PR DESCRIPTION
**Pull request by jasnakai**
Related to [#1565](https://github.com/18F/tock/issues/1565)

This PR covers fixes for the color contrast issues for the `Billable Hours` link as well as the SVG circle indicator and hour totals.

Updates in this PR:
- Section BG from `accent-cool-light` (`#97d4ea`) to `accent-cool-lighter` (`#e1f3f8`) (See Image 1)
- SVG Circle fill to `white` (`#ffffff`) and stroke from `accent-cool-light` (`#97d4ea`) to `gray-20` (`#c9c9c9 `) (See Image 1)
- Hour Total Numbers from `accent-cool-light` (`#97d4ea`) to `base-dark` (`#565c65`) (See Image 1)
Unrelated to issue:
- Removed an empty CSS rule `.reporting-period`

(Image 1)
image

Not covered in this PR:
- Other accessibility issues found while making these updates. Working to add those to their own tickets.

### CODE REVIEW

**Comment by melchoyce** [comment]
Did you mean to write something after `Unrelated to issue:`?

If we can find someone with hourly billing to test this out, I'd love to see how those circles look with hours logged. Otherwise, looks good to me on the design front!

**Review by cantsin — APPROVED** [review]
CSS changes look good. Minor question: why the change in `correct8.svg`?

**Comment by melchoyce** [comment]
> It's a bit hard to see the red on grey but axe doesn't flag it. Thoughts?

What would it look like if the inside of the circle was white? Wondering if that would help with the visibility, since I agree it's a little hard to make out.

**Comment by jasnakai** [comment]
White fill on cricle:
image

**Comment by jasnakai** [comment]
> CSS changes look good. Minor question: why the change in `correct8.svg`?

This image updated when I ran my initial docker build. Not sure if it was/wasn't there to start with?

**Comment by jasnakai** [comment]
> 

This version has a white background and `base-lighter` [#dfe1e2] gray for the stroke. I think I like this on the best.
image

**Comment by melchoyce** [comment]
> This version has a white background and `base-lighter` [#dfe1e2] gray for the stroke. I think I like this on the best.

The red definitely stands out more that way. Is it okay that the light grey doesn't have stronger contrast against the blue or white backgrounds?

**Comment by jasnakai** [comment]
> The red definitely stands out more that way. Is it okay that the light grey doesn't have stronger contrast against the blue or white backgrounds?

From an accessibility stand point, I'd say yes. This is a progressive enhancement. The information is there in text format.
However, we can bump it up to a `gray-20` (`#c9c9c9`). This is what it looks like:
image

**Comment by melchoyce** [comment]
Let's go with that! Thanks 🙌

**Comment by cantsin** [comment]
(as an aside, feel free to merge when you are ready!)

**Comment by jasnakai** [comment]
> (as an aside, feel free to merge when you are ready!)

Thank you but I am not able to merge. The message reads "You're not authorized to merge this pull request."

**Pull request merged**
