### PR TITLE
Test for submitted cards in utilization views

### PR DESCRIPTION
**Pull request by tbaxter-18f**
Makes sure only submitted timecards are used in utilization reports.

### CODE REVIEW

**Comment by Jkrzy** [comment]
Good as-is, this covers excluding non-submitted timecards from utilization reporting. Thanks  @tbaxter-18f! We'll still need to update the `Recent Tocks` table on the `UserDetailView`

**Comment by tbaxter-18f** [comment]
Joe, would you like me to take care of that real quick before we merge this?

**Comment by Jkrzy** [comment]
That would be great, thanks!

**Comment by tbaxter-18f** [comment]
Ready for re-review.

**Pull request merged**
