### PR TITLE
WIP: Upgrade to uswds 2.3.1

### PR DESCRIPTION
**Pull request by cantsin**
## Description

Examining what is involved with an upgrade to USWDS 2.x. Relevant issue: #867

## Additional information

Trying to leave as much intact as possible. Not cleaning up CSS just yet, just migrating to the new 2.x USWDS styling first.

Known issues that won't be fixed: 

- uswds outline for selected nav menu items used to be `2px dotted gray`; new is `2rem blue`

### CODE REVIEW

**Comment by its-a-lisa** [comment]
@cantsin is this still a WIP?

**Comment by cantsin** [comment]
@its-a-lisa yes, still a WIP. currently the biggest obstacle is an `@extend` SCSS hack for forms that I'm trying to work around. And in the meanwhile USWDS has updated to 2.4.0 :stuck_out_tongue_closed_eyes:

**Comment by hbillings** [comment]
I've got some bandwidth for this; happy to pick it up!

**Comment by cantsin** [comment]
@hbillings yay! please do! :raised_hands: I feel guilty for leaving this on the back burner for so long. Main sticking points: 

1. getting rid of `@extend` scss hacks for "raw" django forms in e.g., `user_form` (maybe perhaps using [widget-tweaks](https://pypi.org/project/django-widget-tweaks/))
2. rebasing on current master

Happy to chat about anything else that might be unclear here.

**Comment by tbaxter-18f** [comment]
@cantsin Given the related #996 security warning and @hbillings lack of availability right now, is there any chance you can pick this up again? If not, I _totally_ understand, but I wanted to ask.

**Comment by cantsin** [comment]
@tbaxter-18f I'll see if I can allocate some non billable time next week to work on this PR (alas, I can't promise anything though) -- I will update y'all when I know either way.

**Comment by tbaxter-18f** [comment]
That's all we can ask @cantsin, and if you can't get to it, you can't, and that's OK. Thanks!

**Comment by hursey013** [comment]
@cantsin are these the remaining tasks to get the over the finish line?

> getting rid of @extend scss hacks for "raw" django forms in e.g., user_form (maybe perhaps using widget-tweaks)
> rebasing on current master

If so, could you expand on what needs to be done with the instances of `@extend`? Do we also want to bump the USWDS version to the latest release or stick with `2.3.1`?

**Comment by cantsin** [comment]
@hursey013 I am currently rebasing on `master` and hope to have that work up later today. I think in the interests of expediency, I would keep the `@extend` CSS hacks and stay with `2.3.1` -- we can always update later. (What makes this PR somewhat challenging is that the CSS is in dire need of cleanup.) Open to discussion about all these, though.

**Comment by cantsin** [comment]
Update: wasn't able to push up a rebase, got bogged down on the big one: `hours/timecard_form` -- will continue on Monday.

**Comment by cantsin** [comment]
Closing in favor of https://github.com/18F/tock/pull/1041 -- keeping this branch around for reference until we don't need it anymore

**Pull request closed without merging**
