### PR TITLE
Update day to tock on timesheet alert message

### LINKED ISSUE #524: Alert says to tock on Monday instead of Friday
The alert says:
>Reminder! Please complete your Tock time card for the prior week no later than end of the day on Monday (or the first business day of the following week).

but we've since changed it to Friday, so we need to update this text to be accurate.

Instead it should say:
>Reminder! Please complete your Tock time card for the prior week no later than end of the day on Friday (or the last business day of the week).

cc: @joshuabailes

### PR DESCRIPTION
**Pull request by maya**
Updates day to tock from Monday to Friday on timesheet alert message, to align with our new tocking deadlines.

### This is what it looks like:

screen shot 2016-10-12 at 11 31 50 am

Resolves #524.

cc: @joshuabailes

### CODE REVIEW

**Comment by annalee** [comment]
This might be pedantic, but do we want to axe "prior" here? It could be read as saying that folks have a week to tock their time.

**Comment by maya** [comment]
@annalee good catch! totally agree. removed in d7e5ecf.

**Comment by maya** [comment]
Opened a writing lab issue to copy edit this: https://github.com/18F/writing-lab/issues/214

**Comment by coreycaitlin** [comment]
Edited inline and committed above! Should look like this:

screen shot 2016-10-12 at 5 49 40 pm

Here's my thought process, in case it's useful:

- removed `Reminder` because the styling makes it clear enough
- made the beginning of the first sentence bold so people can tell at a glance that it'll be about the deadline 
- removed both "please" and "no later than", in favor of more direct phrasing
- shortened and simplified sentence about Saturday overtime, and removed extra information about our work week running S-S; that information doesn't help clarify the deadline, and is likely to cause confusion for many users

Feel free to roll back or re-edit as you see fit, of course!

**Comment by coreycaitlin** [comment]
One more tiny commit to clarify the Saturday-work language per @hollyallen's [comment here](https://github.com/18F/tock/issues/510#issuecomment-253305426)

I believe the revised version manages to avoid making Saturday work sound normal/expected, mentions that it should be authorized in some form, and makes the deadline clear.

**Comment by maya** [comment]
@coreycaitlin looks good to me, thanks! @sfvictor @joshuabailes how do these copy edits look to you?

**Comment by maya** [comment]
Content approved by @joshuabailes!

@annalee do you want to merge or should I?

**Pull request merged**
