### PR TITLE
bill-ico-nix

### PR DESCRIPTION
**Pull request by batemapf**
remove the "billable" dollar icon from the timecard form cc @ramirezg. left some extra html in there to preserve existing formatting.  can probably be removed.

### CODE REVIEW

**Comment by ramirezg** [comment]
@batemapf I think we might need to remove the rest before this commit is ready. Should I wait for an update in the next days?

**Comment by batemapf** [comment]
@ramirezg went ahead and got rid of the extra html.  mind taking a look?

**Comment by ramirezg** [comment]
@batemapf I also removed the Javascript, check out the staging site and let me know how it looks.

**Comment by batemapf** [comment]
looks good.  only suggestion (not a request) is that the hours box be
horizontally aligned above the 'total hours:' and the submit button. if you
don't have the time, don't worry about it and just go ahead and push.

On Mon, Oct 19, 2015 at 6:38 PM, Gabriel Ramirez <notifications@github.com>
wrote:

> @batemapf <https://github.com/batemapf> I also removed the Javascript,
> check out the staging site and let me know how it looks.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/18F/tock/pull/233#issuecomment-149367331>.
>



-- 
Patrick F. Bateman
Operations Director (acting)
18F
U.S. General Services Administration

**Comment by ramirezg** [comment]
@batemapf so I don't have enough front end skills to do that well. :(

**Comment by batemapf** [comment]
no worries! if our front end colleagues can't live with the layout as is,
maybe they will volunteer to fix!

On Tue, Oct 20, 2015 at 4:40 PM, Gabriel Ramirez <notifications@github.com>
wrote:

> @batemapf <https://github.com/batemapf> so I don't have enough front end
> skills to do that well. :(
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/18F/tock/pull/233#issuecomment-149695295>.
>



-- 
Patrick F. Bateman
Operations Director (acting)
18F
U.S. General Services Administration

**Pull request merged**
