### PR TITLE
[WIP] 511 addhours endpoint

### PR DESCRIPTION
**Pull request by elg0nz**
## Description
This PR implements #511: an AddHours endpoint that allows a user to add hours for a specific line item to the current time card so that it's easier to contemporaneously track time in Tock.

### CODE REVIEW

**Comment by elg0nz** [comment]
Test failed because of flaky tests where the datetime in the server does not match the time stored on the database. 
```
    self.assertEqual(timecardobj.created.day, datetime.date.today().day)
```

These tests will pass tomorrow morning when the date in GMT matches the date on EST. Please run them again to make the tests green.

To prevent this issue, we recommend setting the TZ env variable on travis.yml  and setting a default django timezone. We'll submit these changes as a separate PR. 

http://stackoverflow.com/a/27052708
https://docs.djangoproject.com/en/1.10/topics/i18n/timezones/#default-time-zone-and-current-time-zone

**Comment by elg0nz** [comment]
@batemapf any comments on this PR?

**Comment by batemapf** [comment]
@elg0nz thanks for the nudge. do you mind submitting a PR without the extraneous commits? 

screen shot 2016-12-01 at 10 12 27 am

cc: @mtorres253

**Comment by elg0nz** [comment]
@batemapf done. The new PR is available at #594 I'll leave this open because this PR is linked to the auction.

**Pull request closed without merging**
