### PR TITLE
Add pull request template

### PR DESCRIPTION
**Pull request by maya**
This adds a pull request template to the repo, which includes a section for "Description" to remind people to write the general changes the PR makes. This will then be used for our public facing emails/change log.

### CODE REVIEW

**Comment by batemapf** [comment]
I'm good with this, @annalee @abrouilette @lauraponce?

**Comment by abrouilette** [comment]
No complaints here.

**Comment by annalee** [comment]
:shipit:

**Comment by maya** [comment]
Looks like this is ✅  - will merge! Thanks all!

**Pull request merged**
