### PR TITLE
Convert Org units from choices to a table

### LINKED ISSUE #965: Convert business units to DB table
Currently the business units are coded as choices in employees/models.py. We need to change to (and migrate the data to) a DB table. We'd like to support sub-disciplines and easier changes.

### PR DESCRIPTION
**Pull request by tbaxter-18f**
## Description

Our hard-coded business units are woefully out of date and inflexible. Updating!
Resolves #965

### CODE REVIEW

**Comment by tbaxter-18f** [comment]
In spite of my mucking about with migrations, I've got a persistent `Related model 'organizations.Unit' cannot be resolved` error here.

**Comment by Jkrzy** [comment]
It looks like we have some migrations missing from `master` unrelated to this change. Let's remedy that before tackling this so we can limit the migrations required for this PR.

**Comment by Jkrzy** [comment]
Updating this against most recent version of `master`

**Comment by tbaxter-18f** [comment]
Closing in favor of a different branch/PR

**Pull request closed without merging**
