### PR TITLE
[WIP] Add max hours to model

### PR DESCRIPTION
**Pull request by batemapf**
The objective of this PR is to prevent users from logging more hours to projects that exceed a pre-specified amount. Logging too many hours results in a budget overage, which itself results in a costly agreement modification.

I am attempting to meet this objective by creating the following workflow: (1) a `staff` or `superuser` marks a project as subject to a `max_hours_restriction`; (2) a `staff` or `superuser` sets a `max_hours` value which is the number of hours that may be billed to a project until the project is automatically deactivated; (3) when an end user submits a `Timecard` and related `TimecardObject`s the `hours_spent` values increment the respective `all_hours_logged` attribute in the `Project` model;  (4) when an end user enters submits a `Timecard` and related `TimecardObject`s that push the the `all_hours_logged` value greater than or equal to the `max_hours` value on a project that has the `max_hours_restriction` attribute marked True, the project automatically deactivates (that is, the `active` value turns to False).

To account for a situation when a user submits a `TimecardObject` that pushes the `all_hours_logged` value beyond the `max_hours` value ("the straw that broke the camel's back" scenario), I have added in a 40 hour static "buffer" that automatically discounts the `max_hours` value by 40 on the theory that no one user can submit a `TimecardObject` with an `hours_spent` attribute that is greater than 40 hours. This **of course** is a pretty clumsy way to do it, but it means I can push off learning forms validation for a little longer :-).

Deploying this branch to staging @ https://tock-staging.18f.gov right now!

### CODE REVIEW

**Comment by batemapf** [comment]
@ccostino when you have a moment, would love to get your thoughts. and yes, i included *all* of the commits 😁

**Comment by batemapf** [comment]
Ah, should also note that while this functionality works well with net new projects, there will need to be a little DB work done with legacy projects (i.e. those that already have hours logged to them). I have some thoughts on this...

**Comment by ccostino** [comment]
Awesome, @batemapf!  Will be happy to work through this!  However, we definitely need to work through some Django forms validation, it's not as bad as you may think. :-)

**Comment by batemapf** [comment]
re: https://github.com/18F/tock/pull/422#issuecomment-240876964:

wrote this to update legacy projects . is effective (and quick!) when used on the staging db via `cf-ssh` and the django interpreter (`manage.py shell`). this is currently at ..app/tock/hours_update.py in the `tock-staging` space.

```
import hours
import projects

all_projects = projects.models.Project.objects.all()
all_projects_num = len(all_projects)
num_check = all_projects_num
all_timecard_objects = hours.models.TimecardObject.objects.all()
results = {}

while all_projects_num >0:
    for p in all_projects:
        if p.all_hours_logged is None:
            p.all_hours_logged = 0
        related_timecard_objects = all_timecard_objects.filter(project=p.id)
        related_timecard_objects_num = len(related_timecard_objects)
        all_hours = 0
        while related_timecard_objects_num > 0:
            for t in related_timecard_objects:
                all_hours += t.hours_spent
                related_timecard_objects_num -= 1
        if p.all_hours_logged < all_hours:
            p.all_hours_logged = all_hours
            p.save()
            results[p.name] = 'Updated with {} hours.'.format(all_hours)
        elif p.all_hours_logged == all_hours:
            results[p.name] = 'Existing hours ({}) match total timecard hours ({}). No update needed.'.format(p.all_hours_logged, all_hours)
        elif p.all_hours_logged > all_hours:
            results[p.name] = 'Existing hours ({}) are greater than total timecard hours ({}). No update made.'.format(p.all_hours_logged, all_hours)
        all_projects_num -= 1
results_num = len(results)
if results_num == num_check:
    for r in results:
        print('{}: {}'.format(r, results[r]))
    print('\n\nSuccessfully reviewed ({}) of ({}). Detailed results are above.\n'.format(results_num, num_check))
else:
    print('\n\nError! Number of projects reviewed ({}) is different than number of number of projects in the database ({})'
        '\nPlease review results and rerun update if necessary.'.format(results_num, num_check))
```

in addition, wrote this tiny complement script update all `all_hours_logged` values for testing purposes (which is also in the `tock-staging` space at hours_clean.py):

```
import hours
import projects

all_projects = projects.models.Project.objects.all()
for p in all_projects:
    p.all_hours_logged = 0.00
    p.save()
```

**Comment by ccostino** [comment]
@batemapf, it's going to take me a bit of time to get to reviewing this, but I'd still love to go through it and if we can find sometime, walk through it together as well!

**Comment by batemapf** [comment]
suspected issue is the ordering of the clean methods. it looks like [new code](https://github.com/18F/tock/pull/422/commits/f3fe191b3e9fb45e8aa8ead9a9362bbadc47684b#diff-c3acdd58ad22b7864da7fe4161e8d3e8R207) is trying to evaluate `NoneType` objects that were cleaned in an [earlier method](https://github.com/18F/tock/blob/master/tock/hours/forms.py#L170). not sure how to proceed. cc @ccostino since we worked through much of this together on friday (but didnt test!)

**Comment by ccostino** [comment]
D'oh, okay, I probably need a bit more of a refresher here than I thought.  Will help take a look soon again unless someone else is able to jump in!

**Comment by batemapf** [comment]
@annalee this is one i'd like to get finished up and definitely need some help. it looks pretty straight forward, but still having trouble with the form validation (see last couple of comments).

**Comment by batemapf** [comment]
@annalee this one is ready for review!

**Summary**

This PR has, ahem, evolved since its creation. The objective is the same, however: to prevent users from logging hours to projects in excess of the amount of hours that the project's budget will support. The execution has changed from relying on the boolean state of the `active` attribute of a `Project` object to being handled via a form `clean()` method.

**Comment by batemapf** [comment]
closing in favor of a human-based solution cc @annalee

**Pull request closed without merging**
